services:
  postgres:
    image: postgres:15
    container_name: puntored_postgres
    environment:
      POSTGRES_DB: puntored_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - puntored_net

volumes:
  postgres_data:

networks:
  puntored_net:
